<table class="signatory">

    <tr>

        <td>

            <div class="line"></div>

            <div class="title">
        Generated By
            </div>

            <div class="designation">
            {{ auth()->user()->name ?? auth()->user()->email }}
            </div>

        </td>

        <td class="spacer"></td>

        <td>

            <div class="line"></div>

            <div class="title">
                Authorized Signature
            </div>

            <div class="designation">
                Bursary/Registry Unit
            </div>

        </td>

    </tr>

</table>
